use_frameworks!

target 'TccSwift_Example' do
  pod 'TccSwift', :path => '../'

  target 'TccSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
